language: python
script:
- cd git-version-builder && python setup.py test
after_success:
- bii user ${BII_USERNAME} -p ${BII_PASSWORD}
- bii publish
#deploy:
#  provider: biicode
#  user: ${BII_USERNAME}
#  password:
#    secure: ${BII_PASSWORD}
#  on:
#    branch: develop

