language: python
sudo: required
script:
- cd git-version-builder && python setup.py test
deploy:
  provider: biicode
  user: ${BII_USERNAME}
  password:
    secure: ${BII_PASSWORD}
  on:
    branch: develop

