language: cpp
sudo: required
compiler:
- gcc
before_install:
- wget https://raw.githubusercontent.com/smessmer/travis-utils/master/update_gcc_version.sh
  && chmod +x update_gcc_version.sh
  && ./update_gcc_version.sh 4.9
  && rm update_gcc_version.sh
before_script:
- wget https://raw.githubusercontent.com/smessmer/travis-utils/master/setup_biicode_project.sh
  && chmod +x setup_biicode_project.sh
  && ./setup_biicode_project.sh
  && rm setup_biicode_project.sh
script:
#The configure line is needed as a workaround for the following link, otherwise we wouldn't need "bii configure" at all because "bii build" calls it: http://forum.biicode.com/t/error-could-not-find-the-following-static-boost-libraries-boost-thread/374
- bii cpp:configure || bii cpp:configure
- bii cpp:build --target messmer_gitversion_test_main -- -j2
- "./bin/messmer_gitversion_test_main"
after_success:
- bii user ${BII_USERNAME} -p ${BII_PASSWORD}
- bii publish
#deploy:
#  provider: biicode
#  user: ${BII_USERNAME}
#  password:
#    secure: ${BII_PASSWORD}
#  on:
#    branch: develop

